pretrained_ckpt_path: 'hf://rail-berkeley/octo-small'
seed: 42
eval_datasets:
- bridge_dataset
eval_interval: 5000
log_interval: 100
num_steps: 300000
prefetch_num_batches: 0
resume_path: null
save_dir: null
save_interval: 10000
start_step: null

window_size: 1
num_inp_channels: 4 # RGBD input
pred_horizon: 1

viz_interval: 20000
viz_kwargs:
  eval_batch_size: 128
  samples_per_state: 8
  trajs_for_metrics: 100
  trajs_for_viz: 8

text_processor:
  args: []
  kwargs:
    encode_with_model: false
    tokenizer_kwargs:
      max_length: 16
      padding: max_length
      return_tensors: np
      truncation: true
    tokenizer_name: t5-base
  module: vlnce_baselines.models.octo.text_processing
  name: HFTokenizer

dataset_kwargs:
  balance_weights: true
  batch_size: 128
  frame_transform_kwargs:
    image_augment_kwargs:
    - augment_order:
      - random_resized_crop
      - random_brightness
      - random_contrast
      - random_saturation
      - random_hue
      random_brightness:
      - 0.1
      random_contrast:
      - 0.9
      - 1.1
      random_hue:
      - 0.05
      random_resized_crop:
        ratio:
        - 0.9
        - 1.1
        scale:
        - 0.8
        - 1.0
      random_saturation:
      - 0.9
      - 1.1
    - augment_order:
      - random_brightness
      - random_contrast
      - random_saturation
      - random_hue
      random_brightness:
      - 0.1
      random_contrast:
      - 0.9
      - 1.1
      random_hue:
      - 0.05
      random_saturation:
      - 0.9
      - 1.1
    num_parallel_calls: 200
    resize_size:
      primary:
      - 256
      - 256
      wrist:
      - 128
      - 128
  oxe_kwargs:
    data_dir: gs://rail-octo-central2/resize_256_256
    data_mix: oxe_magic_soup
    load_camera_views:
    - primary
    - wrist
    load_depth: false
  shuffle_buffer_size: 500000
  traj_read_threads: 48
  traj_transform_kwargs:
    future_action_window_size: 3
    goal_relabeling_strategy: uniform
    subsample_length: 100
    task_augment_kwargs:
      keep_image_prob: 0.5
    task_augment_strategy: delete_task_conditioning
    window_size: 2
  traj_transform_threads: 48

model:
  heads:
    action:
      args: []
      kwargs:
        action_dim: 6
        pred_horizon: ${pred_horizon}
        readout_key: readout_action
        use_map: false
        embedding_size: ${model.token_embedding_size}
      module: vlnce_baselines.models.octo.action_heads
      name: DiffusionActionHead
  max_horizon: 10
  observation_tokenizers:
    primary:
      args: []
      kwargs:
        encoder:
          args: []
          kwargs:
            num_inp_channels: ${num_inp_channels} # NOTE: task_stack_keys is empty
          module: vlnce_baselines.models.octo.vit_encoders
          name: SmallStem16
        obs_stack_keys:
        - image_primary
        task_stack_keys: []
        finetune_encoder: true
      module: vlnce_baselines.models.octo.tokenizers
      name: ImageTokenizer
  readouts:
    action: 1
  task_tokenizers:
    language:
      args: []
      kwargs:
        encoder: t5-base
        finetune_encoder: false
      module: vlnce_baselines.models.octo.tokenizers
      name: LanguageTokenizer
  max_tokens: ${text_processor.kwargs.tokenizer_kwargs.max_length}
  token_embedding_size: 384
  transformer_kwargs:
    add_position_embedding: false
    attention_dropout_rate: 0.0
    dropout_rate: 0.0
    mlp_dim: 1536
    num_attention_heads: 6
    num_layers: 3 #12
    window_size: ${window_size}
    token_embedding_size: ${model.token_embedding_size}

optimizer:
  clip_gradient: 1.0
  frozen_keys:
  - '*hf_model*'
  learning_rate:
    init_value: 0.0
    name: rsqrt
    peak_value: 0.0003
    timescale: 10000
    warmup_steps: 2000
  weight_decay: 0.1

pretrained_loaders:
- args: []
  kwargs:
    hf_model: 'google-t5/t5-base'
  module: octo.utils.train_utils
  name: hf_weights_loader

val_kwargs:
  num_val_batches: 16
  val_shuffle_buffer_size: 1000



