BASE_TASK_CONFIG_PATH: habitat_extensions/config/rxr_vlnce_english_task.yaml
TRAINER_NAME: octo_trainer
SIMULATOR_GPU_IDS: [1] # Evals run on these GPUs
TORCH_GPU_ID: 2
NUM_ENVIRONMENTS: 5 # Number of envs per GPU
TENSORBOARD_DIR: outputs/rxr_octo_en
CHECKPOINT_FOLDER: outputs/rxr_octo_en
CONTEXT_LEARNING: False
OCTO_CONFIG_PATH: '/home/saumyas/Projects/VLN-CE-Plan/vlnce_baselines/config/rxr_baselines/rxr_octo_config.yaml'

wandb:
  entity: iam-lab
  group: octo_full
  project: vlnce_plan
  name: octo_full_instr_diffusion_action_head_history3_pred4
  saver:
    upload: True
    save_top_k: 5
wandb_resume_id: null

EVAL:
  USE_CKPT_CONFIG: True
  SPLIT: val_seen
  LANGUAGES: [en-US, en-IN]
  EPISODE_COUNT: -1
  SAMPLE: True
  SAVE_VIDEO: False
  VIDEO_SAVE_FREQ: 500
  VIDEO_SAVE_LOC: ['disk'] # options: "disk", "tensorboard"
  SAVE_RESULTS: False
  logger_type: 'wandb' # 'wandb', 'tb'
  wandb_load:
    run_path: 'iam-lab/vlnce_plan/wbjwe454'
    file: checkpoints/ckpt_epoch_0_step_12060_action_loss_3.535.pth
    entity: iam-lab
    project: vlnce_plan_eval
    group: octo
    name: subtasks_diffusion_action_head
  tb_load:
    EVAL_CKPT_PATH_DIR: outputs/rxr_octo_en_subtasks/2024_01_16-15_35_57/checkpoints/ckpt.14.pth # If this is a directory, evaluate all checkpoints. Else evaluate the specified checkpoint.pth
    EVAL_LOG_DIR: outputs/rxr_octo_en_subtasks/2024_01_16-15_35_57

  EVAL_TASK_CONFIG:
    TASK:
      SUCCESS_DISTANCE: 3.0
      SUCCESS:
        SUCCESS_DISTANCE: 3.0
      SUCCESS_NO_STOP:
        SUCCESS_DISTANCE: 3.0
      ORACLE_SUCCESS:
        SUCCESS_DISTANCE: 3.0
      NDTW:
        SUCCESS_DISTANCE: 3.0
    ENVIRONMENT:
      MAX_EPISODE_STEPS: 300
  COMMON:
    SIMULATOR_GPU_IDS: [1] # Evals run on these GPUs
    NUM_ENVIRONMENTS: 10 # Number of envs per GPU
    TORCH_GPU_ID: 0

MODEL:
  policy_name: OctoPolicy
  INSTRUCTION_ENCODER:
    bidirectional: True
    sensor_uuid: rxr_instruction
    embedding_size: 768

RL:
  POLICY:
    OBS_TRANSFORMS:
      ENABLED_TRANSFORMS: [ResizeShortestEdge, CenterCropperPerSensor]
      CENTER_CROPPER_PER_SENSOR:
        SENSOR_CROPS:
          rgb: (256, 256)
          depth: (256, 256)

IL:
  batch_size: 3
  epochs: 15
  inflection_weight_coef: 1.9
  load_from_ckpt: False
  ckpt_to_load: outputs/rxr_octo_en_subtasks/2024_01_12-14_46_50/checkpoints/ckpt.14.pth

  OCTO_TRAINER:
    effective_batch_size: 6
    scale_bits: 1.0 # used when action_repr=bits
    preload_size: 30
    preload_trajectories_file: False
    trajectories_file: data/trajectories_dirs/rxr_en_guide_trim250/trajectories.json.gz
    max_traj_len: 250  # 1.3% of episodes in the English training split are above 250
    logger_type: 'wandb' # 'wandb', 'tb'

train:
  optimizer:
    name: AdamW
    Adam:
      lr: 2.5e-4
      eps: 1.0e-8
    AdamW:
      lr: 2.5e-4
      eps: 1.0e-8
      weight_decay: 0.01

  # Scheduler config
  scheduler:
    use: True
    name: timm_cosine
    CosineAnnealingLR:
      eta_min: 0.00001
      t_max: -1
      last_epoch: -1    # No warm restarts (simply follows cosine decay)
    timm_cosine:
      use_timm: True
      sched: cosine
      # epochs are updated in code: epochs <- total_epochs - warmup - cooldown
      epochs: 15  # Total epochs to run (warmup + decay + cooldown)
      min_lr: 1.0e-6         # k
      warmup_lr: 1.0e-5
      warmup_epochs: 1
      cooldown_epochs: 7

  grad_clip:
    use: True
    norm: 1.0